# Dependencies
markdown:         kramdown
highlighter:      rouge
kramdown:
  input: GFM

# Permalinks
permalink:        pretty

# Setup
title:            'ATX Open Data'
tagline:          'ATX Open Data Initiative'
description:      ''
# url:              http://cityofaustin.github.io/open-data-docs
baseurl:          /open-data-docs

author:
  name:           ''
  url:            ''

paginate:         5

gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/cityofaustin/open-data-docs
